
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_reactive
      username: root
      password: ''
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryAutoConfiguration, org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration, org.springframework.boot.autoconfigure.data.r2dbc.R2dbcRepositoriesAutoConfiguration
#    show-sql: true